modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/Bawnorton/RuntimeTrims/issues"
license = "MIT"

[[mods]]
modId = "runtimetrims"
version = "${version}"
displayName = "RuntimeTrims"
authors = "Bawnorton"
description = '''
${description}
'''
logoFile = "assets/runtimetrims/icon.png"

[[mixins]]
config = "runtimetrims.mixins.json"

[[mixins]]
config = "runtimetrims-client.mixins.json"

[[dependencies.runtimetrims]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"

[[dependencies.runtimetrims]]
modId = "configurable"
type = "required"
versionRange = ">=2.2.0"
ordering = "NONE"
side = "BOTH"